### ISSUE TITLE
IT does not rename the package name

### ISSUE THREAD

**Issue by samir1010** [yeppao/fastlane-plugin-android_change_package_name#1]
Hi  i am an android developer ,
In Android Studio project my projects package name in the Manifestfile.xml is  - com.khanlab.halloween
and under this i have different sub packages 
i want to rename the package name com.khanlab.halloween to com.khanlab.fastlanedemo  (changes is reflected in Manifest.xml and in build gradle)  but in my project under Java folder  it does not rename the package name .
It keeps the the pevious package - com.khanlab.halloween and creates a new package under halloween named fastlanedemo

And the Manifestfile could not locate the targeted activity as the package name changes, and every thing is red colored in the Manifest.xml

**Comment by yeppao** [comment]
Hey didnt see you comment, did you need still need it to be solved ?

**Comment by yeppao** [comment]
Reopen this issue if you have some examples
